import React from "react";

const COLUMNS = {
  company_name: {
    title: "Company Name",
  },
  contact_number: {
    title: "Contact number",
  },
  name: {
    title: "Name",
  },
  tag_id: {
    title: "Tag ID",
  },
  vehicle_number: {
    title: "Vehicle Number",
  },
  vehicle_type: {
    title: "Vehicle Type",
  },
  flat_number: {
    title: "Flat Number",
  },
  email_id: {
    title: "Email ID",
  },
  tag_expiry: {
    title: "Tag Expiry",
  },
  tag_remarks: {
    title: "Tag Remark",
  },
  action_by: {
    title: "Action By",
  },
  audit_type: {
    title: "Edit Tag",
  },
  remarks: {
    title: "Remarks",
  },
  updated: {
    title: "Updated at",
  },
  vehicle_no: {
    title: "Vehicle Number",
  },
  charge_status: {
    title: "Slot Allocation Type",
  },
};
const results = [
  {
    id: 1049570,
    tag_id: "1802",
    project_id: 129,
    vehicle_number: "ABCD12345",
    name: "Prayag",
    vehicle_type: "Car",
    wheel_count: 4,
    contact_number: "9790716835",
    email_id: "test1@gmail.com",
    registered_on_app: true,
    tag_remarks: true,
    status: true,
    control_type: "Manual",
    emergency_open: false,
    tag_expiry: false,
    tag_lost: false,
    charge_status: "fcfs",
    company_id: "",
    category_id: 9,
    tag_lock_feature: true,
    flat_number: ["Flat - 23"],
    user_id: 660416,
    unit_list: [],
    created: "2021-02-02",
    updated: "2021-04-13",
    company_name: null,
    category: null,
  },
  {
    id: 1049569,
    tag_id: 1801,
    project_id: 129,
    vehicle_number: "DL3SC09749",
    name: "Test",
    vehicle_type: "Car",
    wheel_count: 4,
    contact_number: "9790716887",
    email_id: "test2@gmail.com",
    registered_on_app: null,
    tag_remarks: false,
    status: false,
    control_type: "Manual",
    emergency_open: false,
    tag_expiry: true,
    tag_lost: false,
    charge_status: "fcfs",
    company_id: "",
    category_id: 9,
    tag_lock_feature: true,
    flat_number: ["Flat - 21"],
    user_id: "",
    unit_list: [],
    created: "2021-02-02",
    updated: "2021-02-02",
    company_name: null,
    category: null,
  },
  {
    id: 1049573,
    tag_id: "1802",
    project_id: 129,
    vehicle_number: "MS11A1751",
    name: "Bhupendra",
    vehicle_type: "Car",
    wheel_count: 4,
    contact_number: "9790716845",
    email_id: "test3@gmail.com",
    registered_on_app: true,
    tag_remarks: true,
    status: true,
    control_type: "Manual",
    emergency_open: false,
    tag_expiry: false,
    tag_lost: false,
    charge_status: "fcfs",
    company_id: "",
    category_id: 9,
    tag_lock_feature: true,
    flat_number: ["Flat - 22"],
    user_id: 660416,
    unit_list: [],
    created: "2021-02-02",
    updated: "2021-04-13",
    company_name: null,
    category: null,
  },
];